# Section 2: Basic Python Programming

## Introduction to programming concepts:

### Output

In [10]:
# Print strings
print("Hello there")
print('Hello there')
print('The is "Mohammed" from Pycad')
print("This is Mohammed's Channel")

# Print numbers
print(1)

# Print a mix
print("My age is:", 27, 34, 45, "fgs", "refedf", 45, sep="-", end="\r")
print('This is a second line')

Hello there
Hello there
The is "Mohammed" from Pycad
This is Mohammed's Channel
1
This is a second linegs-refedf-45


### Input

In [18]:
input()

'hi'

In [19]:
input()

'4'

In [17]:
int(input())

4

--------------------------------------------------------------

## Data Types and Variables:

In [1]:
int_var = 3
float_var = 3.5
string_var = "Pycad"
char_var = "C"
bool_var = True
list_var = []
dict_var = {}

In [29]:
print(type(int_var), type(float_var), type(string_var), type(char_var), type(list_var), type(dict_var))

<class 'int'> <class 'float'> <class 'str'> <class 'str'> <class 'list'> <class 'dict'>


### Lists

In [41]:
new_list = ['something', 1]

In [34]:
print(new_list)

['something', 1]


In [36]:
type(new_list[1])

int

In [37]:
new_list.append('added word')

In [38]:
new_list

['something', 1, 'added word']

In [39]:
new_list.clear()

In [40]:
new_list

[]

In [2]:
int_list = [3,5,1,9,0]

In [44]:
int_list.sort()

In [45]:
int_list

[0, 1, 3, 5, 9]

In [52]:
print(int_list[0])
print(int_list[0:1])
print(int_list[:])
print(int_list[:-1])
print(int_list[:1])
print(int_list[2:])
print(int_list[-2:])

0
[0]
[0, 1, 3, 5, 9]
[0, 1, 3, 5]
[0]
[3, 5, 9]
[5, 9]


In [3]:
print(0 in int_list)

True


In [4]:
int_list.index(0)

4

### Strings

In [ ]:
string_var = 'The Pycad Team is growing'

----------------------------------------------------

## Conditional Statements and Loops:

### Conditional Statements

In [ ]:
# Example of if statement in Python
x = 5
if x > 0:
    print("x is positive")

### For Loop

In [ ]:
# Example of for loop in Python
for i in range(5):
    print(i)

### While Loop

In [ ]:
# Example of while loop in Python
i = 0
while i < 5:
    print(i)
    i += 1

-------------------------------------------------------------

## Functions:

In [2]:
# Example of a function in Python
def greet(name):
    print("Hello, " + name + "!")

# Calling the function with a parameter
greet("John")

Hello, John!


----------------------------------------------------------

## Modules and Packages:

In [3]:
# Example of importing a module in Python
import math

# Using a function from the math module
x = math.sqrt(25)

In [4]:
# Example of importing a specific function from a module
from random import randint

# Using the randint function from the random module
y = randint(1, 100)

---------------------------------------------------------------

## File Handling:

In [5]:
# Example of writing to a file in Python
file = open("myfile.txt", "w")
file.write("Hello, World!")
file.close()

In [6]:
# Example of reading from a file in Python
file = open("myfile.txt", "r")
content = file.read()
print(content)
file.close()

Hello, World!


-----------------------------------------------------------

# Section 4: Python Libraries for Medical Imaging

## OS

In [33]:
import os

# generating a path
path = os.path.join('part1', 'part2', 'part3', 'part4', 'part5', 'part6')
path

'part1\\part2\\part3\\part4\\part5\\part6'

In [35]:
# Return the filename from the path
filename = os.path.basename(path)
filename

'part6'

In [36]:
# Create a folder or set of folders
os.makedirs(path)

---------------------------------------------------

## Glob

In [38]:
from glob import glob

my_path = 'path/to/files/*'
files_paths = glob(my_path)
files_paths

[]

In [41]:
# List all PNG files in the current directory
png_files = glob('*.png')
png_files

[]

In [42]:
# List all files in subdirectories recursively
all_files = glob('**/*', recursive=True)
all_files

['basic_python.ipynb', 'data', 'README.md']

In [43]:
# List all files with a name starting with "image" and ending with ".png"
image_files = glob('image*.png')
image_files

[]

--------------------------------------------------------

## NumPy

In [7]:
import numpy as np

# Creating a 1D array with 5 elements
a = np.array([1, 2, 3, 4, 5])

# Creating a 2D array with 2 rows and 3 columns
b = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 3D array with 2 layers, 3 rows, and 4 columns
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [8]:
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
c[0][0]

array([1, 2, 3, 4])

### Commun opetations

In [29]:
d = np.transpose(b)
e = np.rot90(b)
f = np.min(b)
g = np.max(b)
h = np.unique(b)
i, j = np.unique(b, return_counts=True)

### Save & Load NumPy arrays (.npy)

In [ ]:
# Save a numpy array
np.save('outfile.npy', x)

In [ ]:
# Load a numpy array
np_array = np.load('infile.npy')

------------------------------------------------------------------

## Matplotlib

### Displaying a 2D Image:

In [ ]:
import matplotlib.pyplot as plt

# Load a 2D image
img = plt.imread('image.png')

# Display the image using Matplotlib
plt.imshow(img, cmap='gray')
plt.title('2D Image')
plt.show()

### Displaying a 3D Volume:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Load a 3D volume
vol = np.load('volume.npy')

# Display a slice of the volume using Matplotlib
plt.imshow(vol[:,:,50], cmap='gray')
plt.title('3D Volume Slice')
plt.show()

### Displaying Multiple Images in a Grid:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Load multiple 2D images
img1 = plt.imread('image1.png')
img2 = plt.imread('image2.png')
img3 = plt.imread('image3.png')

# Display the images in a grid using Matplotlib
fig, axes = plt.subplots(1, 3, figsize=(10, 5))
axes[0].imshow(img1, cmap='gray')
axes[0].set_title('Image 1')
axes[1].imshow(img2, cmap='gray')
axes[1].set_title('Image 2')
axes[2].imshow(img3, cmap='gray')
axes[2].set_title('Image 3')
plt.show()

### Displaying a Histogram of Pixel Intensities:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Load a 2D image
img = plt.imread('image.png')

# Display a histogram of the pixel intensities using Matplotlib
plt.hist(img.flatten(), bins=256, range=(0, 1))
plt.title('Pixel Intensity Histogram')
plt.show()

### Displaying Image Segmentation Results:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Load a 2D image and its segmentation mask
img = plt.imread('image.png')
mask = np.load('mask.npy')

# Display the image and its segmentation mask using Matplotlib
fig, axes = plt.subplots(1, 2, figsize=(10, 5))
axes[0].imshow(img, cmap='gray')
axes[0].set_title('Image')
axes[1].imshow(mask, cmap='gray')
axes[1].set_title('Segmentation Mask')
plt.show()